dist: trusty
branches:
  only:
  - master
  - develop
  - /^[Rr]elease\/(.*)/
  - /^[Ff]eature\/(.*)/
  - /^[Hh]otfix\/(.*)/
language: node_js
node_js:
- 9.2
cache: yarn
notifications:
  emails: false
install:
- yarn install
script:
- yarn lint
- yarn test
- yarn build
