dist: trusty
language: node_js
node_js:
  - 9.2
install:
  - yarn install
script:
  - yarn lint
  - yarn test
  - yarn build
cache: yarn
notifications:
  emails: false
branches:
  only:
    - master
    - develop
    - \[Rr]elease\/(.*)\
    - \[Ff]eature\/(.*)\
    - \[Hh]otfix\/(.*)\
